---
apiVersion: v1
data:
  TZ: America/Denver
kind: ConfigMap
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant-config-extraconf
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-assistant"
    tailscale.com/tags: "tag:home-assistant"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - envFrom:
        - configMapRef:
            name: home-assistant-config-extraconf
        image: ghcr.io/home-assistant/home-assistant:2025.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: home-assistant-app
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: ha-config-root
          # Bluetooth
        - mountPath: /dev/ttyACM0
          name: ttyacm
        - mountPath: /run/dbus
          name: dbus
        - mountPath: /dev/ttyUSB0
          name: ttyusb
      restartPolicy: Always
      volumes:
      - name: ha-config-root
        hostPath:
          path: /media/data-ssd/home-assistant
          type: DirectoryOrCreate
      # Bluetooth
      - name: ttyacm
        hostPath:
          path: /dev/ttyACM0
      # Zigbee USB
      - name: ttyusb
        hostPath:
          path: /dev/ttyUSB0
      - name: dbus
        hostPath:
          path: /run/dbus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: TZ
              value: "America/Denver"
          image: ghcr.io/home-assistant-libs/python-matter-server:8.1
          ports:
            - containerPort: 5580
              protocol: TCP
          name: matter-server
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /data
              name: matter-data
      restartPolicy: Always
      volumes:
        - name: matter-data
          hostPath:
            path: /media/data-ssd/home-assistant/matter-server
            type: DirectoryOrCreate
        # Bluetooth
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        # Zigbee USB
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  ports:
    - name: "matter-websocket"
      port: 5580
      targetPort: 5580
  selector:
    app: matter-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go2rtc
  name: go2rtc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go2rtc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go2rtc
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - image: docker.io/alexxit/go2rtc:1.9.14
          imagePullPolicy: Always
          name: go2rtc
          # For MDNS
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          env:
            - name: TZ
              value: "America/Denver"
          ports:
            - name: go2rtc
              containerPort: 1984
              protocol: TCP
            - name: go2rtc-rtsp
              containerPort: 8554
              protocol: TCP
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          volumeMounts:
            - mountPath: /config
              name: go2rtc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: go2rtc
          hostPath:
            path: /media/data-ssd/home-assistant/go2rtc
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "go2rtc"
    tailscale.com/tags: "tag:home-assistant"
  labels:
    app: go2rtc
  name: go2rtc
  namespace: default
spec:
  ports:
    - name: "go2rtc"
      port: 80
      protocol: TCP
      targetPort: go2rtc
    - name: "go2rtc-rtsp"
      port: 8554
      protocol: TCP
      targetPort: go2rtc-rtsp
  selector:
    app: go2rtc
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "frigate"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/5r2mzxzqbozrmctx6qthzqgouy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frigate
  name: frigate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frigate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - image: ghcr.io/blakeblackshear/frigate:stable
          imagePullPolicy: Always
          name: frigate
          # For MDNS
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          env:
            - name: FRIGATE_RTSP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: frigate
                  key: password
          ports:
            - name: frigate
              containerPort: 8971
              protocol: TCP
            - name: frigate-rtsp
              containerPort: 8554
              protocol: TCP
            - name: frigate-rtc
              containerPort: 8555
              protocol: TCP
            - name: frigate-rtc-udp
              containerPort: 8555
              protocol: UDP
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          volumeMounts:
            - mountPath: /config
              name: frigate-config
            - mountPath: /media/frigate
              name: frigate-media
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: frigate-config
          hostPath:
            path: /media/data-ssd/home-assistant/frigate/config
            type: DirectoryOrCreate
        - name: frigate-media
          hostPath:
            path: /media/data-ssd/home-assistant/frigate/media
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frigate"
    tailscale.com/tags: "tag:home-assistant"
  labels:
    app: frigate
  name: frigate
  namespace: default
spec:
  ports:
    - name: "frigate"
      port: 80
      protocol: TCP
      targetPort: frigate
    - name: frigate-rtsp
      port: 8554
      protocol: TCP
      targetPort: frigate-rtsp
    - name: frigate-rtc
      port: 8555
      protocol: TCP
      targetPort: frigate-rtc
    - name: frigate-rtc-udp
      port: 8555
      protocol: UDP
      targetPort: frigate-rtc-udp
  selector:
    app: frigate
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "eufy"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/2bt7kfmjowtpqsvdvqvewn7ase"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eufy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eufy
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - image: docker.io/bropat/eufy-security-ws:1.9
          imagePullPolicy: Always
          name: scrypted
          env:
            - name: PORT
              value: "3000"
            - name: TRUSTED_DEVICE_NAME
              value: "eufy-security-ws"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: password
          ports:
            - name: eufy
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: eufy-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: eufy-data
          hostPath:
            path: /media/data-ssd/home-assistant/eufy
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "eufy"
    tailscale.com/tags: "tag:home-assistant"
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  ports:
    - name: "eufy"
      port: 80
      protocol: TCP
      targetPort: eufy
  selector:
    app: eufy
