---
apiVersion: v1
data:
  TZ: America/Denver
kind: ConfigMap
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant-config-extraconf
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "home-assistant"
    tailscale.com/tags: "tag:http"
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: home-assistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
        app.kubernetes.io/name: home-assistant
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - envFrom:
        - configMapRef:
            name: home-assistant-config-extraconf
        image: ghcr.io/home-assistant/home-assistant:2025.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        name: home-assistant-app
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - SYS_ADMIN
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 0
          periodSeconds: 10
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 30
          initialDelaySeconds: 0
          periodSeconds: 5
          tcpSocket:
            port: 8123
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: ha-config-root
          # Bluetooth
        - mountPath: /dev/ttyACM0
          name: ttyacm
        - mountPath: /run/dbus
          name: dbus
        - mountPath: /dev/ttyUSB0
          name: ttyusb
      restartPolicy: Always
      volumes:
      - name: ha-config-root
        hostPath:
          path: /media/data-ssd/home-assistant
          type: DirectoryOrCreate
      # Bluetooth
      - name: ttyacm
        hostPath:
          path: /dev/ttyACM0
      # Zigbee USB
      - name: ttyusb
        hostPath:
          path: /dev/ttyUSB0
      - name: dbus
        hostPath:
          path: /run/dbus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: TZ
              value: "America/Denver"
          image: ghcr.io/home-assistant-libs/python-matter-server:8.1
          ports:
            - containerPort: 5580
              protocol: TCP
          name: matter-server
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /data
              name: matter-data
      restartPolicy: Always
      volumes:
        - name: matter-data
          hostPath:
            path: /media/data-ssd/home-assistant/matter-server
            type: DirectoryOrCreate
        # Bluetooth
        - name: ttyacm
          hostPath:
            path: /dev/ttyACM0
        # Zigbee USB
        - name: ttyusb
          hostPath:
            path: /dev/ttyUSB0
        - name: dbus
          hostPath:
            path: /run/dbus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matter-server
  name: matter-server
  namespace: default
spec:
  ports:
    - name: "matter-websocket"
      port: 5580
      targetPort: 5580
  selector:
    app: matter-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scrypted
  name: scrypted
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrypted
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scrypted
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - image: ghcr.io/koush/scrypted:intel
          imagePullPolicy: Always
          name: scrypted
          # For MDNS
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
          env:
            - name: SCRYPTED_NVR_VOLUME
              value: "/nvr"
            - name: SCRYPTED_INSECURE_PORT
              value: "11080"
          ports:
            - name: scrypted-http
              containerPort: 11080
              protocol: TCP
            - name: scrypted-https
              containerPort: 10443
              protocol: TCP
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          volumeMounts:
            - mountPath: /server/volume
              name: scrypted-db
            - mountPath: /nvr
              name: scrypted-nvr
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: scrypted-db
          hostPath:
            path: /media/data-ssd/home-assistant/scrypted/db
            type: DirectoryOrCreate
        - name: scrypted-nvr
          hostPath:
            path: /media/data-ssd/home-assistant/scrypted/nvr
            type: DirectoryOrCreate
# Unencrypted http endpoint for tailscale
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "scrypted"
    tailscale.com/tags: "tag:http"
  labels:
    app: scrypted
  name: scrypted-http
  namespace: default
spec:
  ports:
    - name: "scrypted"
      port: 80
      protocol: TCP
      targetPort: scrypted-http
  selector:
    app: scrypted
# HTTPS for internal cluster traffic
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "scrypted-https"
    tailscale.com/tags: "tag:http"
  labels:
    app: scrypted
  name: scrypted-https
  namespace: default
spec:
  ports:
    - name: "scrypted-https"
      port: 443
      protocol: TCP
      targetPort: scrypted-https
  selector:
    app: scrypted
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "eufy"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/2bt7kfmjowtpqsvdvqvewn7ase"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eufy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eufy
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
        - image: docker.io/bropat/eufy-security-ws:1.9
          imagePullPolicy: Always
          name: scrypted
          env:
            - name: PORT
              value: "3000"
            - name: TRUSTED_DEVICE_NAME
              value: "eufy-security-ws"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eufy
                  key: password
          ports:
            - name: eufy
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: eufy-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: eufy-data
          hostPath:
            path: /media/data-ssd/home-assistant/eufy
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "eufy"
    tailscale.com/tags: "tag:http"
  labels:
    app: eufy
  name: eufy
  namespace: default
spec:
  ports:
    - name: "eufy"
      port: 80
      protocol: TCP
      targetPort: eufy
  selector:
    app: eufy
