---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: protonmail-bridge
  name: protonmail-bridge
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - image: docker.io/shenxn/protonmail-bridge:3.19.0-1
        name: protonmail-bridge
        ports:
        - name: smtp
          containerPort: 25
        - name: imap
          containerPort: 143
        volumeMounts:
        - name: protonmail-bridge-data
          mountPath: /root/
      volumes:
      - name: protonmail-bridge-data
        hostPath:
          path: /opt/protonmail-bridge
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: protonmail-bridge
  name: protonmail-bridge
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "protonmail-bridge"
    tailscale.com/tags: "tag:protonmailbridge"
spec:
  ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: smtp
  - name: imap
    port: 143
    protocol: TCP
    targetPort: imap
  selector:
    app: protonmail-bridge
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ferroxide
  name: ferroxide
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferroxide
  template:
    metadata:
      labels:
        app: ferroxide
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - image: docker.io/heywoodlh/ferroxide:2026_01
        name: ferroxide
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "ferroxide -config-home /config -carddav-host 0.0.0.0 -caldav-host 0.0.0.0 -disable-imap -disable-smtp serve" ]
        ports:
        - name: carddav
          containerPort: 8080
        - name: caldav
          containerPort: 8081
        volumeMounts:
        - name: ferroxide-config
          mountPath: /config
      volumes:
      - name: ferroxide-config
        hostPath:
          path: /opt/protonmail-bridge/ferroxide
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ferroxide
  name: ferroxide
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "dav"
    tailscale.com/tags: "tag:protonmailbridge"
spec:
  ports:
  - name: carddav
    port: 8080
    protocol: TCP
    targetPort: carddav
  - name: caldav
    port: 8081
    protocol: TCP
    targetPort: caldav
  selector:
    app: ferroxide
  type: ClusterIP
