---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rsshub-browserless
  name: rsshub-browserless
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsshub-browserless
  template:
    metadata:
      labels:
        app: rsshub-browserless
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - image: docker.io/browserless/chrome:1.61-puppeteer-13.1.3
        name: rsshub-browserless
        ports:
        - name: browserless
          containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsshub-browserless
  name: rsshub-browserless
  namespace: default
spec:
  ports:
  - name: rsshub-browserless
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rsshub-browserless
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rsshub-redis
  name: rsshub-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsshub-redis
  template:
    metadata:
      labels:
        app: rsshub-redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - image: docker.io/redis:7.4.5
        name: rsshub-redis
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
        - name: rsshub-redis-data
          mountPath: /data
      volumes:
      - name: rsshub-redis-data
        hostPath:
          path: /opt/rsshub/redis
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsshub-redis
  name: rsshub-redis
  namespace: default
spec:
  ports:
  - name: rsshub-redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: rsshub-redis
  type: ClusterIP
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "rsshub"
  namespace: "default"
spec:
  itemPath: "vaults/Kubernetes/items/dvcsamqty7467ditg2wrehgiym"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rsshub
  name: rsshub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsshub
  template:
    metadata:
      labels:
        app: rsshub
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab
      containers:
      - image: docker.io/diygod/rsshub:2025-02-19
        name: rsshub
        ports:
        - name: rsshub
          containerPort: 1200
        env:
        - name: NODE_ENV
          value: "1"
        - name: CACHE_TYPE
          value: "redis"
        - name: REDIS_URL
          value: "redis://rsshub-redis:6379/"
        - name: PUPPETEER_WS_ENDPOINT
          value: "ws://rsshub-browserless:3000"
        - name: YOUTUBE_KEY
          valueFrom:
            secretKeyRef:
              name: rsshub
              key: youtube_key
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rsshub
  name: rsshub
  namespace: default
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "rsshub"
    tailscale.com/tags: "tag:http"
spec:
  ports:
  - name: rsshub
    port: 80
    protocol: TCP
    targetPort: 1200
  selector:
    app: rsshub
  type: ClusterIP
