---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "skyrim-together"
  namespace: "gaming"
spec:
  itemPath: "vaults/Kubernetes/items/xmbn3b7aeg5wejbw5bodxpruwa"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skyrim-together
  name: skyrim-together
  namespace: gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skyrim-together
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skyrim-together
    spec:
      containers:
        - env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: skyrim-together
                  key: admin-password
            - name: ALLOW_CONNECT_PLATFORM
              value: Steam
          image: docker.io/tiltedphoques/st-reborn-server:v1.8.0
          imagePullPolicy: Always
          name: skyrim-together-server
          ports:
            - name: skyrim-together
              containerPort: 10578
              protocol: UDP
          resources:
            limits:
              cpu: 2000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /st-server/config
              name: stserver-config
            - mountPath: /st-server/Data
              name: stserver-data
            - mountPath: /st-server/logs
              name: stserver-logs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: stserver-config
          hostPath:
            path: /media/data-ssd/st-server/config
            type: DirectoryOrCreate
        - name: stserver-data
          hostPath:
            path: /media/data-ssd/st-server/data
            type: DirectoryOrCreate
        - name: stserver-logs
          hostPath:
            path: /media/data-ssd/st-server/logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "skyrim"
    tailscale.com/tags: "tag:skyrim-together"
  labels:
    app: skyrim-together
  name: skyrim-together
  namespace: gaming
spec:
  ports:
    - name: "skyrim-together"
      port: 10578
      protocol: UDP
      targetPort: skyrim-together
  selector:
    app: skyrim-together
