---
- name: Install curl
  ansible.builtin.package:
    name: curl

- name: Check if Nix store exists
  ansible.builtin.stat:
    path: "/nix"
  register: nix_store_check

- name: Install Nix
  ansible.builtin.shell: |
    curl -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
  when:
    - not nix_store_check.stat.exists
    - ansible_os_family != 'Alpine'

- name: alpine linux tasks to install nix
  when: ansible_os_family == 'Alpine'
  block:
    - name: install nix dependencies
      community.general.apk:
        name: git,bash

    - name: install nix
      community.general.apk:
        name: nix
        update_cache: true

    - name: ensure nix group exists
      ansible.builtin.group:
        name: nix
        state: present

    - name: add heywoodlh to nix group
      ansible.builtin.user:
        name: heywoodlh
        groups: nix
        append: yes

    - name: add alpine-specific config
      ansible.builtin.lineinfile:
        path: /etc/nix/nix.conf
        line: "{{ item }}"
        create: yes
      loop:
        - "!include nix.custom.conf"

    - name: enable nix-daemon service
      ansible.builtin.service:
        name: nix-daemon
        enabled: true
        state: started

- name: Add nix to $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/nix-path.sh
    content: 'PATH=$PATH:/nix/var/nix/profiles/default/bin'
  when: ansible_os_family != 'Alpine'

- name: check if connected to tailscale
  ansible.builtin.uri:
    url: http://attic.barn-banana.ts.net
  register: tailscale_server_check
  ignore_errors: true

- name: copy tailscale nix.conf
  when: tailscale_server_check.status == 200
  ansible.builtin.copy:
    src: etc/nix/nix.tailscale.conf
    dest: /etc/nix/nix.custom.conf
  register: nix_ts_conf

- name: copy non-tailscale nix.conf
  when: tailscale_server_check.status != 200
  ansible.builtin.copy:
    src: etc/nix/nix.conf
    dest: /etc/nix/nix.custom.conf
  register: nix_conf

- name: restart nix-daemon service
  ansible.builtin.service:
    name: nix-daemon
    enabled: true
    state: restarted
  when: nix_ts_conf.changed or nix_conf.changed
