---
collections:
  - name: community.kubernetes
    version: "2.0.1"
  - name: operator_sdk.util
    version: "0.5.0"
  - name: kubernetes.core
    version: "5.4.1"
  - name: cloud.common
    version: "4.2.0"
  - name: community.docker
    version: "5.0.4"
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "12.4.0"
  - name: ansible.windows
    version: "3.3.0"
  - name: prometheus.prometheus
    version: "0.27.4"

roles:
  - name: geerlingguy.docker
    version: "7.9.0"
